"""update security table fields and constraints

Revision ID: 13582c9486b0
Revises: 879722c47318
Create Date: 2026-08-16 01:30:42.816501

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "13582c9486b0"
down_revision: Union[str, Sequence[str], None] = "879722c47318"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("security", sa.Column("symbol", sa.String(length=10), nullable=False))
    op.drop_constraint(op.f("security_ticker_key"), "security", type_="unique")
    op.create_unique_constraint(None, "security", ["symbol"])
    op.drop_column("security", "ticker")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "security",
        sa.Column("ticker", sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "security", type_="unique")
    op.create_unique_constraint(
        op.f("security_ticker_key"),
        "security",
        ["ticker"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("security", "symbol")
    # ### end Alembic commands ###
