services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    container_name: investment-api-dev

    volumes:
      - ..:/workspaces/investment-api

    command: sleep infinity