services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    container_name: atlas-api-dev

    volumes:
      - ..:/workspaces/atlas-api

    command: sleep infinity